[package]
name = "match-details"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
memmap2 = "0.9.4"
serde = "1.0"
serde_json = "1.0"
source2-demo = { path = "../../source2-demo", features = ["deadlock"] }