[package]
name = "d2-stampede"
description = "Dota 2 replay parser written in Rust"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
d2-stampede-protobufs = { path = "../d2-stampede-protobufs", version = "0.1.0" }

snap = "1.1.1"
regex = { version = "1.10.4", features = ["std", "unicode-perl"], default-features = false }
bitter = "0.6.2"
rustc-hash = "1.1.0"
nohash-hasher = "0.2.0"
lazy_static = "1.4.0"
anyhow = "1.0.82"
libmimalloc-sys = "=0.1.35"
mimalloc = { version = "=0.1.39", default-features = false, optional = true }

[features]
default = ["mimalloc", "unsafe_reader"]
unsafe_reader = []
