[workspace]
members = [
    "d2-stampede",
    "d2-stampede-protobufs",
    "d2-stampede-observers",
    "d2-stampede-examples/*",
    "d2-stampede-macros"]

resolver = "2"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"

