[package]
name = "chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
d2-stampede = { version = "0.2", path = "../../d2-stampede" }
memmap2 = "0.9.4"
anyhow = "1.0"
