[package]
name = "stampede-examples"
version = "0.1.0"
edition = "2021"
#build= "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stampede = { path = ".." }

[profile.dev]
opt-level = 0

[profile.release]
#debug=true
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[features]
entities = []
