[package]
name = "d2-stampede-protobufs"
version = "0.1.0"
edition = "2021"
build = "build.rs"
exclude = ["protos/*"]

[lib]
path = "./lib.rs"

[build-dependencies]
prost-build = "0.12.3"

[dependencies]
prost = "0.12.3"