[package]
name = "d2-stampede-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
d2-stampede-protobufs = { version = "0.2.0", path = "../d2-stampede-protobufs" }
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"